task_1_texts_with_label_collisions = [
    ("Electric vehicle manufacturers, components for the vehicles, batteries and producers for charging infrastructure who invest over Rs 50 crore and create at least 50 jobs stand eligible for total SGST (State GST) refund on their sales till end of calendar year 2030.", "1"),
    ("NewsPeople  Thomas Cook: What to do if you're on holiday or have a trip booked with the collapsed travel giant A major operation to bring home around 150,000 people currently on Thomas Cook holidays is underway after the company announced it had ceased trading.", "1"),
    ("For disposals on or after 29 October 2018, they must also satisfy one of the following tests: a distribution test  -  an individual is entitled to at least 5% of the company's profit available for distribution to equity holders and 5% of the assets available for distribution to equity holders in a winding up or a proceeds test  -  an individual is entitled to at least 5% of the proceeds in the event of a disposal of the whole of the ordinary share capital of the company.", "1")
]
task_2_texts_with_fact_collisions = [
    "With more than 275 members, covering the whole spectrum of the listed real estate industry (companies, investors and their suppliers), EPRA represents over EUR 450 billion of real estate assetsand 94% of the market capitalisation of the FTSE EPRA Nareit Europe Index. EPRA's mission is to promote, develop and represent the European public real estate sector. We achieve this through the provision of better information to investors and stakeholders, active involvement in the public and political debate, promotion of best practices and the cohesion and strengthening of the industry.",
    "For 2019 and onwards, the speculation and vacancy tax rate will vary, depending on residency and where owners pay income tax. Those rates will be two per cent for foreign owners and satellite families and 0.5 per cent for British Columbians and other Canadian citizens or permanent residents who are not members of a satellite family  As of its first quarterly report, the ministry is forecasting revenue of $185 million in 2019-20 and $185 million in 2020-21."
]
